---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: kube101
  labels:
    app: kube101-demo
spec:
  replicas: 3
  selector:
    matchLabels:
      app: kube101-demo
  template:
    metadata:
      labels:
        app: kube101-demo
    spec:
      containers:
      - name: kube101-demo
        image: aniketgawade/kube101-demo-image
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: kube101
spec:
  selector:
    app: kube101-demo

  ports:
  type: NodePort
  ports:
  - port: 80
    nodePort: 30003
  type: NodePort